name: GUT Unit Tests
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: "barichello/godot-ci:4.7"

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Import project
        run: godot --headless --import --quit

      - name: Run Tests
        run: |
          godot \
            --headless \
            -d \
            --path "$PWD" \
            -s addons/gut/gut_cmdln.gd \
            -gconfig=.gutconfig.json \
            -gcompact_mode \
            -gexit
